[workspace]
members = ["rlay-core", "rlay-macros"]

[package]
name = "rlay"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
piet = "0.7.0"
rlay-macros = { path = "./rlay-macros" }
rlay-core = { path = "./rlay-core" }
